---
title: "Data Exploration"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
```


```{r}
## 데이터 가져오기
raw_welfare <- read.csv('../data-files/selected_welfare.csv')
```


```{r}
## 데이터 복사
welfare <- raw_welfare
```


```{r}
 # 데이터 구조 확인
str(welfare)
head(welfare)
```


## 성별에 따른 월급 차이

```{r}
# 성별 데이터 확인 ( 1 : 남, 2 : 여, 9 : 모름/무응답 )
table(welfare$sex)
```
```{r}
# 성별 데이터를 수치 데이터 -> 문자열 데이터로 변경
welfare$sex <- ifelse(welfare$sex == 1, 'male', 'female')
table(welfare$sex)
```

```{r}
qplot(welfare$sex)
```


```{r}
# 급여 데이터 확인 ( 범위 : 1 ~ 9998, 모름/무응답 : 9999)
summary(welfare$income)
```

```{r}
# income의 0, 9999 -> NA 처리
welfare$income <- ifelse(welfare$income %in% c(0, 9999), NA, welfare$income)
# NA 분포 확인
table( is.na(welfare$income) )
```


```{r}
# NA를 제거한 성별 급여 평균
income_by_gender <- welfare %>% 
  filter(!is.na(income)) %>% 
  group_by(sex) %>% 
  summarise(income_mean = mean(income))

income_by_gender
```

```{r}
ggplot(income_by_gender, aes(x = sex, y = income_mean)) + geom_bar(stat='identity')
```

## 나이와 급여 사이의 관계

```{r}
# 데이터 구조 다시보기
str(welfare)

# birth 데이터로 age 데이터로 사용
# brith 분포 확인 ( 범위 : 1900 ~ 2014, 9999 : 모름 / 무응답 )
summary(welfare$birth)

# NA 여부 확인
table( is.na(welfare$birth) )
```

```{r}
# 출생년도를 사용해서 2015년 기준 나이 계산해서 새로운 컬럼에 저장
welfare <- welfare %>% 
  mutate(age = 2015 - birth + 1)

# 나이 데이터 분포 확인
summary(welfare$age)
```

```{r}
qplot(welfare$age)
```

```{r}
# NA인 inome을 제외하고 연령별로 급여 평균 계산
income_by_age <- welfare %>% 
  filter(!is.na(income)) %>% 
  group_by(age) %>%
  summarise(income_mean = mean(income))

income_by_age
```


```{r}
ggplot(income_by_age, aes(x = age, y = income_mean)) + geom_line()
```

```{r}
# 연령대 변수 만들기 ( ~ 30 / 30 ~ 60 / 60 ~ )
welfare <- welfare %>% 
  mutate(age2 = ifelse(age < 30, 
                       'young', 
                       ifelse(age < 60, 'middle', 'old')))
table(welfare$age2)
qplot(welfare$age2)
```
```{r}
# 연령대별로 급여 평균
income_by_age2 <- welfare %>% 
  filter(!is.na(income)) %>% 
  group_by(age2) %>% 
  summarise(income_mean = mean(income))

income_by_age2
ggplot(income_by_age2, aes(x = age2, y = income_mean)) + geom_bar(stat='identity')
```
```{r}
# 성별, 연령대별 급여 비교

income_by_age2_and_gender <- welfare %>% 
  filter(!is.na(income)) %>% 
  group_by(age2, sex) %>% 
  summarise(income_mean = mean(income))

income_by_age2_and_gender
ggplot(income_by_age2_and_gender, aes(x = age2, y = income_mean, fill = sex)) + geom_bar(stat='identity', position = 'dodge')
```
```{r}
# 연령별, 성별 급여 분석
income_by_age_and_gender <- welfare %>% 
  filter(!is.na(income)) %>% 
  group_by(age, sex) %>% 
  summarise(income_mean = mean(income),
            n = n())

income_by_age_and_gender

ggplot(income_by_age_and_gender, aes(x = age, y = income_mean, col = sex)) + geom_line()
```
```{r}
# 종교와 결혼상태(이혼) 관계 분석
# 결혼상태 데이터 탐색 ( 0 : 18세미만    1 : 유배우    2 : 사별    3 : 이혼    4 : 별거   5 : 미혼    6 : 기타)
class(welfare$marriage)
table(welfare$marriage)

# 이혼여부 컬럼 추가 ('marriage', 'divorce', NA)
welfare <- welfare %>% 
  mutate(marriage2 = ifelse(marriage == 1, 
                            'marriage', 
                            ifelse(marriage == 3, 'divorce', NA)))

table(is.na(welfare$marriage2))
qplot(welfare$marriage2)
```
```{r}
# 종교 데이터 탐색 ( 1: 있음, 2 : 없음, 9: 모름/무응답 )
table(welfare$religion)

# 데이터를 숫자 -> 문자열
welfare$religion <- ifelse(welfare$religion == 1, "yes", "no")
table(welfare$religion)

```

```{r}
# 종교와 결혼상태를 기준으로 빈도, 빈도비율 계산
religion_marriage <- welfare %>% 
  filter(!is.na(marriage2)) %>% 
  group_by(religion, marriage2) %>% 
  summarise(n = n()) %>% 
  mutate(total = sum(n)) %>%
  mutate(pct = round(n / total * 100, 1))
  
```


```{r}
religion_marriage
```
```{r}
# 이혼에 해당하는 데이터만 뽑기
divorce <- religion_marriage %>% 
  filter(marriage2 == 'divorce') %>% 
  select(religion, pct)

divorce

```

```{r}
ggplot(divorce, aes(x = religion, y = pct)) + geom_bar(stat="identity")
```

```{r}

```

```{r}

```

```{r}


```

























